import { Button } from '@/components/ui/button';
import { useLanguage } from '@/contexts/LanguageContext';
import { Home } from 'lucide-react';
import { Link } from 'react-router-dom';
import LanguageSelector from '@/components/LanguageSelector';

import { useEffect, useRef } from 'react';

// PLACEHOLDER: Paste your complete embed snippet here (e.g., the HTML code from publicalbum.org)
const ALBUM_EMBED_SNIPPET = `
  <script src="https://cdn.jsdelivr.net/npm/publicalbum@latest/embed-ui.min.js" async></script>
<div class="pa-gallery-player-widget" style="width:100%; height:480px; display:none;"
  data-link="https://photos.app.goo.gl/ncjNZS9WZQHmyFgU9"
  data-title="Wedding · Saturday, Jun 20 📸"
  data-description="Shared album · Tap to view!">
  <object data="https://lh3.googleusercontent.com/pw/AP1GczOqj8X1GV1eoOn2sf9D0HUb-bUlNAwr0vO-CQQi2XA9V9QVqSUslOcPykrpTzPLWl2lke_bpXI0CZSbV4VfHpRBDWENZbcuXlllpSUOYnbhci5nLTo0=w1920-h1080"></object>
</div>

`;

// Helper component to safely render HTML snippets that contain <script> tags (like PublicAlbum widgets)
const EmbedContainer = ({ html }: { html: string }) => {
  const containerRef = useRef<HTMLDivElement>(null);

  useEffect(() => {
    if (!containerRef.current) return;
    // Inject HTML
    containerRef.current.innerHTML = html;

    // React's dangerouslySetInnerHTML doesn't execute <script> tags.
    // We need to manually recreate and append them for widgets to work.
    const scripts = containerRef.current.querySelectorAll('script');
    scripts.forEach((oldScript) => {
      const newScript = document.createElement('script');
      Array.from(oldScript.attributes).forEach((attr) => newScript.setAttribute(attr.name, attr.value));
      newScript.text = oldScript.innerHTML;
      oldScript.parentNode?.replaceChild(newScript, oldScript);
    });
  }, [html]);

  return <div ref={containerRef} className="w-full h-full flex-1 rounded-lg bg-gray-50/50 overflow-hidden" />;
};

const Pictures = () => {
  const { language } = useLanguage();

  const titles: Record<string, string> = {
    es: 'Fotos',
    it: 'Foto',
    scn: 'Fotografii',
    en: 'Pictures',
  };

  const descriptions: Record<string, string> = {
    es: 'Aquí puedes ver y compartir los recuerdos de la boda',
    it: 'Qui puoi vedere e condividere i ricordi del matrimonio',
    scn: 'Ccà pôi vìdiri e spartìri li ricordi dû matrimoniu',
    en: 'Here you can view and share the wedding memories',
  };

  return (
    <div className="min-h-screen bg-gradient-romantic py-20 flex flex-col">
      <div className="fixed top-4 left-4 z-50">
        <Link to="/">
          <Button variant="outline" size="sm" className="bg-background/80 backdrop-blur-sm">
            <Home className="w-4 h-4 mr-2" />
            {language === 'es' ? 'Inicio' :
              language === 'it' ? 'Home' :
                language === 'scn' ? 'Casa' :
                  'Home'}
          </Button>
        </Link>
      </div>

      <div className="fixed top-4 right-4 z-50">
        <LanguageSelector />
      </div>

      <div className="container mx-auto px-4 flex-1 flex flex-col">
        <div className="text-center mb-8">
          <h1 className="font-script text-5xl md:text-7xl text-primary mb-4">
            {titles[language] || titles.en}
          </h1>
          <p className="text-muted-foreground text-lg">
            {descriptions[language] || descriptions.en}
          </p>
        </div>

        <div className="max-w-6xl mx-auto w-full flex-1 flex flex-col bg-white/50 backdrop-blur-sm rounded-xl shadow-romantic overflow-hidden border border-white/20 p-2 md:p-4 min-h-[60vh] md:min-h-[75vh]">
          {/* 
            Paste the snippet generated by an embed tool directly into the ALBUM_EMBED_SNIPPET constant above.
            The EmbedContainer will handle executing any required widget scripts.
          */}
          <EmbedContainer html={ALBUM_EMBED_SNIPPET} />
        </div>
      </div>
    </div>
  );
};

export default Pictures;
